on:
  push:
  workflow_dispatch:
    inputs:
      validate_certs:
        description: 'Use SSL? (validate_certs)'
        required: true
        default: false
        type: choice
        options:
        - true
        - false
      job_template:
        description: 'The Job Template name you want to launch'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: controller
        uses: ansible-cloud/aap_controller_action@v1.0.1
      # Use the output from the `hello` step
      - name: The job template being executed
        run: echo "The job template is ${{ steps.controller.inputs.job_template }}"
