on:
  push:
  workflow_dispatch:
    inputs:
      validate_certs:
        description: 'Use SSL? (validate_certs)'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      job_template:
        description: 'The Job Template name you want to launch'
        required: true
        type: string


jobs:
  # automation_controller_job:
  #   runs-on: ubuntu-latest
  #   name: Kick off Automation controller job
  #   steps:
  #     - name: Load the ansible-cloud action
  #       id: controller_job
  #       uses: ansible-cloud/aap_controller_action@v1.2.7
  #       with:
  #         controller_host: ${{ secrets.CONTROLLER_HOST }}
  #         controller_username: ${{ secrets.CONTROLLER_USERNAME }}
  #         controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
  #         job_template: "AWS - ec2 enforce owner tag"
  #         extra_vars: "your_region=us-west-1"
  #         validate_certs: false
  workshop_job_provision:
    runs-on: ubuntu-latest
    name: Test provision workshop and teardown
    steps:
      - name: Load the ansible-cloud action for provision
        id: workshop_provision
        uses: ansible-cloud/aap_controller_action@v1.2.7
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          job_template: "Workshop Provision Job"
          extra_vars: "ec2_name_prefix=github-action-test-sean"
          validate_certs: false
      - name: Load the ansible-cloud action for teardown
        id: workshop_teardown
        uses: ansible-cloud/aap_controller_action@v1.2.7
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          job_template: "Teardown Workshop"
          extra_vars: "ec2_name_prefix=github-action-test-sean"
          validate_certs: false
