on:
  push:
  workflow_dispatch:
    inputs:
      validate_certs:
        description: 'Use SSL? (validate_certs)'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      job_template:
        description: 'The Job Template name you want to launch'
        required: true
        type: string

jobs:
  automation_controller_job:
    runs-on: ubuntu-latest
    name: Kick off Automation controller job
    steps:
      - name: Load the ansible-cloud action
        id: controller
        uses: ansible-cloud/aap_controller_action@v1.0.5
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          validate_certs: false
          job_template: "AWS - ec2 enforce owner tag"
          extra_vars: ""
      - name: The job template being executed
        run: echo "The job template is ${{ steps.controller.inputs.job_template }}"
